# Generated by Django 5.1.1 on 2024-09-20 16:31

import crudapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_auto_20240920_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=crudapp.models.get_default_course, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='crudapp.course'),
        ),
    ]
